//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportIn_Webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Registration
    {
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Updates { get; set; }
        public Nullable<bool> status { get; set; }
        public string UserName { get; set; }
        public string ImageUrl { get; set; }
        public string Mobile { get; set; }
    }
}
